### PR TITLE
SLING-8540 - ACL permissions from jcr_root are not correctly serialised

### PR DESCRIPTION
**Pull request by andreituicu**

### CODE REVIEW

**Comment by rombert** [comment]
Thanks for the submission @andreituicu . Note that some tests failed, was this intended>

**Comment by andreituicu** [comment]
@rombert No, it is not intended, but I see that those tests are failing on master as well for a few builds now. On my local machine all unit tests pass, so I don't believe the problem is introduced by this PR.

**Comment by rombert** [comment]
Interesting. I guess @simonetripodi would know best, he seems to be the main contributor so I'll leave it up to him.

**Comment by simonetripodi** [comment]
resolved in 43ee3c0833c9c22786c708239e82a670b2472e6c with a different approach, thanks both for your help!

**Pull request closed without merging**
