### PR TITLE
SLING-11865 - Conversion fails when initial content document does not include namespace declaration

### PR DESCRIPTION
**Pull request by rombert**
Added failing test

### CODE REVIEW

**Comment by kwin** [comment]
IMHO throwing an exception for undeclared namespace prefixes is reasonable here (although in the past this might have been silently ignored). @rombert Do you think that this should just be logged and conversion should continue?

**Comment by rombert** [comment]
@kwin - I think it's important to preserve the current behaviour and give consumers a chance to gradually adapt. I think warn + proceed with the conversion is fine, as long as the docview file is still generated. For the record, the content loader will happily process this file, given that the JCR repository has the correct mappings.

I think we can also introduce a switch to the cpconverter that allows opt-in to the stricter behaviours that we introduce, so that once a content-package passes with strict checks they can be enabled.

**Comment by kwin** [comment]
> as long as the docview file is still generated. 

That is impossible as the docview will be invalid (it has to have a proper namespace URL for the prefix). How did the old version of cp2fm behave for that IT? Which docview file has been generated, what was stripped? I don't think this ever was a behaviour which is worth to keep to be honest.

**Comment by rombert** [comment]
... which is something that was working before. I am not making a technical argument, I am making an argument for not needlessly breaking customer projects.

**Comment by kwin** [comment]
So your proposal is to keep generating invalid XMLs unless user opted in to fail in that case?

For me 

>  not needlessly breaking customer projects.

is incorrect here. I see a need to break here as generating invalid XML (with undeclared prefixes) may easily trigger follow-up issues which are close to impossible to detect then.

**Comment by reschke** [comment]
FWIW (not taking a position on the other points): undeclared prefixes *are* fatal in XML with namespace processing active. That said, XML *without* namespace processing would be able to parse these files, but leave the namespace processing to the application invoking the XML processor. For JCR DocView import, namespace-aware parsing is required by the JCR spec.

**Comment by rombert** [comment]
> So your proposal is to keep generating invalid XMLs unless user opted in to fail in that case?

You can call it that way, yes. You can also formulate it as "we are releasing a minor version of the cp converter that might break existing projects, because of a refactoring". Given that our toolchain worked before, I think this is a drastic move and should be reconsidered.

> I see a need to break here as generating invalid XML (with undeclared prefixes) may easily trigger follow-up issues which are close to impossible to detect then.

I'm not sure I follow. I think we are in one of the two scenarios:

| Namespace present in Initial-Content file  | Namespace declared in Repository | Outcome |
| ------------- | ------------- |------------- |
| No  | Yes  | Installation proceeds, based on the repository namespace mapping |
| No  | No  | Installation is halted |

What we are doing is changing the outcome of the first scenario. Since no one actually complained about the lenient namespace handling and this only came up after a refactoring I am confident this was not a real problem to solve. That is not to say the refactoring was not valuable, I am very glad that it was done, but we should not introduce such behaviour changes.

**Comment by kwin** [comment]
There is no simple solution here except for reverting the https://issues.apache.org/jira/browse/SLING-11421 as the FileVault serializer cannot generate invalid DocView XML. Also I don't have capacity to work on a workaround here for the moment (and also my motivation is limited given

> I see a need to break here as generating invalid XML (with undeclared prefixes) may easily trigger follow-up issues which are close to impossible to detect then.

So I would actually appreciate taking this matter to the mailing list to gather more opinions on it but I am also fine with reverting (but this will obviously reintroduce the old bugs which have been fixed by SLING-11421).

**Comment by rombert** [comment]
> There is no simple solution here except for reverting the https://issues.apache.org/jira/browse/SLING-11421 as the FileVault serializer cannot generate invalid DocView XML. Also I don't have capacity to work on a workaround here for the moment (and also my motivation is limited given
> 
> > I see a need to break here as generating invalid XML (with undeclared prefixes) may easily trigger follow-up issues which are close to impossible to detect then.
> 
> So I would actually appreciate taking this matter to the mailing list to gather more opinions on it but I am also fine with reverting (but this will obviously reintroduce the old bugs which have been fixed by [SLING-11421](https://issues.apache.org/jira/browse/SLING-11421)).

I think reverting would be a shame. I'll take this to the mailing list, thanks for the clarification.

**Comment by rombert** [comment]
No longer needed since https://github.com/adobe/aemanalyser-maven-plugin/pull/205 has fixed the problem I was running into.

**Pull request closed without merging**
