### PR TITLE
SLING-10234 recalculate package type for converted packages

### PR DESCRIPTION
**Pull request by kwin**

### CODE REVIEW

**Comment by kwin** [comment]
The test `ContentPackage2FeatureModelConverterTest.filteredOutContentPackagesAreExcludedDependencies()` now fails with an NPE and I don't really know why. Any idea?

**Comment by karlpauls** [comment]
@kwin, I don't know why the test fails, but the reason was for sure that it was confusing is that it was getting a hidden nullpointer. I pushed a quick fix to your branch for it.

**Comment by kwin** [comment]
Finally figured out that the test only works if test_dep_b-1.0 is detected as type "mixed". That was not the case because the folder /apps and /libs were empty which are just disregarded when the package is extracted.

**Review by karlpauls — APPROVED** [review]
Looks good as far as I can see.

**Pull request merged**
