### PR TITLE
SLING-10401 change scope to 'compile' to not hide dependencies for

### PR DESCRIPTION
**Pull request by kwin**
upstream consumers

### CODE REVIEW

**Comment by cziegeler** [comment]
What problem does this solve? Doesn't make it harder for downstream users to use different versions of the libraries in combination with the converter?

**Comment by kwin** [comment]
For changing versions you use `dependencyManagement`. But the downstream consumers should only declare those dependencies they use directly not transitively!

**Comment by kwin** [comment]
Compare also with the long discussion in https://issues.apache.org/jira/browse/MNG-2205. IMHO using `provided` is just plain wrong for dependencies of simple JARs which are not supposed to be used in OSGi context or a servlet container. I think the approach from https://issues.apache.org/jira/browse/MNG-2205?focusedCommentId=15150313&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15150313 is reasonable and that is what I did in this PR. I fail to see how this could introduce regressions....

**Comment by cziegeler** [comment]
I don't think that there is a right or a wrong approach here - every approach has its benefits. We can have long debates over it and will most likely not agree at the end. So if you think this is the way forward, please do so

**Review by karlpauls — APPROVED** [review]
I at least verified that the resulting zip is the same and it works for in a scenario where I use the converter as a dependency. Ultimately, I agree with @cziegeler, we can debate this forever - hence, if you, @kwin, think this is the way to go feel free to merge. 

I'm planning to cut a release soon so either merge or close it I guess.

**Pull request merged**
