### PR TITLE
SLING-8578 - Nodes which contain : are not correctly processed

### PR DESCRIPTION
**Pull request by andreituicu**

### CODE REVIEW

**Comment by simonetripodi** [comment]
thank you so much @andreituicu for this great addition, very appreciated!

Just two observations:
 
 * there should no need to add an extra path field to the Acl class;
 * you can invoke `Paths.get(PlatformNameFormat.getRepositoryPath(path)` directly in https://github.com/apache/sling-org-apache-sling-feature-cpconverter/blob/master/src/main/java/org/apache/sling/feature/cpconverter/handlers/RepPolicyEntryHandler.java#L163

Please let me know if you don't have enough spare time to push these small polishing operations, I'll take care of merging your PR then I'll optimise it.

Thanks again!

**Comment by andreituicu** [comment]
@simonetripodi I thought the two paths might be needed that's why I created the extra field.
I'll let you optimise it, as you know best the codebase. I looked a bit, but couldn't figure out how to write a meaningful unit test if I implement it how you proposed. :)

Thank you!

**Comment by andreituicu** [comment]
@simonetripodi you can also close this PR if it easier to implement it directly in the optimal way. Thank you!

**Comment by simonetripodi** [comment]
Thanks again @andreituicu for your contribution!

**Pull request merged**
